export const translations: any = {
  en: {
    title: "Find Government Schemes You Deserve",
    subtitle: "India's AI-powered welfare navigator — free, instant, trusted",
    button: "Check My Eligibility",
    form_title: "Tell Us About Yourself",
    form_subtitle: "We'll match you with schemes you qualify for",
    name: "Full Name",
    age: "Your Age",
    gender: "Gender",
    state: "State / UT",
    category: "Category",
    occupation: "Occupation",
    income: "Annual Family Income",
    special: "Special Conditions",
    next: "Next →",
    back: "← Back",
    submit: "Find My Schemes 🎯",
    results_title: "Schemes Found For You",
    results_none: "No schemes found. Try adjusting your details.",
    eligible: "✔ Eligible",
    apply: "Apply Now →",
    ask_ai: "Ask Sahayak AI 🤖",
    loading: "Finding your schemes...",
    chat_title: "Sahayak AI",
    chat_subtitle: "Your personal government scheme assistant",
    chat_placeholder: "Ask anything about schemes...",
    send: "Send",
    thinking: "Sahayak is thinking...",
    scheme_count: "schemes found for you",
    documents: "Documents Needed",
    benefit: "Benefit",
    step: "Step",
    of: "of",
    male: "Male",
    female: "Female",
    other: "Other",
    general: "General",
    obc: "OBC",
    sc: "SC",
    st: "ST",
    student: "Student",
    farmer: "Farmer",
    business: "Business / Self-employed",
    employed: "Salaried / Job",
    unemployed: "Unemployed",
    below1L: "Below ₹1 Lakh",
    "1to2L": "₹1L – ₹2L",
    "2to5L": "₹2L – ₹5L",
    above5L: "Above ₹5 Lakh",
    bpl: "BPL Card Holder",
    disabled: "Differently Abled",
    woman_entrepreneur: "Woman Entrepreneur",
    minority: "Minority Community",
    hero_stat1: "1000+ Schemes",
    hero_stat2: "22 Languages",
    hero_stat3: "Free Forever",
    how_title: "How It Works",
    how1_title: "Tell Us About You",
    how1_desc: "Share basic details — age, income, state, category",
    how2_title: "AI Matches Schemes",
    how2_desc: "Our AI finds every scheme you're eligible for",
    how3_title: "Apply with Guidance",
    how3_desc: "Get step-by-step help to claim your benefits",
  },
  hi: {
    title: "अपनी सरकारी योजनाएं खोजें",
    subtitle: "भारत का AI-संचालित कल्याण सहायक — मुफ्त, तत्काल, विश्वसनीय",
    button: "पात्रता जांचें",
    form_title: "अपनी जानकारी भरें",
    form_subtitle: "हम आपके लिए सबसे उपयुक्त योजनाएं खोजेंगे",
    name: "पूरा नाम",
    age: "आयु",
    gender: "लिंग",
    state: "राज्य / केंद्र शासित प्रदेश",
    category: "श्रेणी",
    occupation: "व्यवसाय",
    income: "वार्षिक पारिवारिक आय",
    special: "विशेष स्थितियां",
    next: "आगे →",
    back: "← वापस",
    submit: "योजनाएं खोजें 🎯",
    results_title: "आपके लिए मिली योजनाएं",
    results_none: "कोई योजना नहीं मिली। अपनी जानकारी बदलकर देखें।",
    eligible: "✔ पात्र हैं",
    apply: "आवेदन करें →",
    ask_ai: "सहायक AI से पूछें 🤖",
    loading: "आपकी योजनाएं खोजी जा रही हैं...",
    chat_title: "सहायक AI",
    chat_subtitle: "आपका निजी सरकारी योजना सहायक",
    chat_placeholder: "योजनाओं के बारे में कुछ भी पूछें...",
    send: "भेजें",
    thinking: "सहायक सोच रहा है...",
    scheme_count: "योजनाएं आपके लिए मिलीं",
    documents: "आवश्यक दस्तावेज",
    benefit: "लाभ",
    step: "चरण",
    of: "में से",
    male: "पुरुष",
    female: "महिला",
    other: "अन्य",
    general: "सामान्य",
    obc: "OBC",
    sc: "SC",
    st: "ST",
    student: "छात्र",
    farmer: "किसान",
    business: "व्यवसाय / स्व-रोजगार",
    employed: "नौकरी / वेतनभोगी",
    unemployed: "बेरोजगार",
    below1L: "₹1 लाख से कम",
    "1to2L": "₹1L – ₹2L",
    "2to5L": "₹2L – ₹5L",
    above5L: "₹5 लाख से अधिक",
    bpl: "BPL कार्ड धारक",
    disabled: "दिव्यांग",
    woman_entrepreneur: "महिला उद्यमी",
    minority: "अल्पसंख्यक समुदाय",
    hero_stat1: "1000+ योजनाएं",
    hero_stat2: "22 भाषाएं",
    hero_stat3: "हमेशा मुफ्त",
    how_title: "यह कैसे काम करता है",
    how1_title: "अपनी जानकारी दें",
    how1_desc: "बुनियादी विवरण साझा करें — आयु, आय, राज्य, श्रेणी",
    how2_title: "AI योजनाएं खोजता है",
    how2_desc: "हमारा AI हर योजना खोजता है जिसके लिए आप पात्र हैं",
    how3_title: "मार्गदर्शन से आवेदन करें",
    how3_desc: "लाभ प्राप्त करने के लिए चरण-दर-चरण सहायता पाएं",
  },
  mr: {
    title: "तुमच्यासाठी सरकारी योजना शोधा",
    subtitle: "भारताचे AI-चालित कल्याण सहाय्यक — मोफत, त्वरित, विश्वासार्ह",
    button: "पात्रता तपासा",
    form_title: "तुमची माहिती भरा",
    form_subtitle: "आम्ही तुमच्यासाठी योग्य योजना शोधू",
    name: "पूर्ण नाव",
    age: "वय",
    gender: "लिंग",
    state: "राज्य",
    category: "वर्ग",
    occupation: "व्यवसाय",
    income: "वार्षिक कौटुंबिक उत्पन्न",
    special: "विशेष परिस्थिती",
    next: "पुढे →",
    back: "← मागे",
    submit: "योजना शोधा 🎯",
    results_title: "तुमच्यासाठी योजना सापडल्या",
    results_none: "कोणती योजना सापडली नाही. माहिती बदलून पहा.",
    eligible: "✔ पात्र आहात",
    apply: "अर्ज करा →",
    ask_ai: "सहायक AI ला विचारा 🤖",
    loading: "तुमच्या योजना शोधत आहोत...",
    chat_title: "सहायक AI",
    chat_subtitle: "तुमचा वैयक्तिक सरकारी योजना सहाय्यक",
    chat_placeholder: "योजनांबद्दल काहीही विचारा...",
    send: "पाठवा",
    thinking: "सहायक विचार करत आहे...",
    scheme_count: "योजना तुमच्यासाठी सापडल्या",
    documents: "आवश्यक कागदपत्रे",
    benefit: "फायदा",
    step: "चरण",
    of: "पैकी",
    male: "पुरुष",
    female: "महिला",
    other: "इतर",
    general: "सामान्य",
    obc: "OBC",
    sc: "SC",
    st: "ST",
    student: "विद्यार्थी",
    farmer: "शेतकरी",
    business: "व्यवसाय / स्व-रोजगार",
    employed: "नोकरी / पगारदार",
    unemployed: "बेरोजगार",
    below1L: "₹1 लाखापेक्षा कमी",
    "1to2L": "₹1L – ₹2L",
    "2to5L": "₹2L – ₹5L",
    above5L: "₹5 लाखापेक्षा जास्त",
    bpl: "BPL कार्डधारक",
    disabled: "दिव्यांग",
    woman_entrepreneur: "महिला उद्योजक",
    minority: "अल्पसंख्याक समुदाय",
    hero_stat1: "1000+ योजना",
    hero_stat2: "22 भाषा",
    hero_stat3: "नेहमी मोफत",
    how_title: "हे कसे काम करते",
    how1_title: "तुमची माहिती द्या",
    how1_desc: "मूलभूत तपशील सांगा — वय, उत्पन्न, राज्य, वर्ग",
    how2_title: "AI योजना शोधतो",
    how2_desc: "आमचा AI तुम्ही पात्र असलेल्या प्रत्येक योजना शोधतो",
    how3_title: "मार्गदर्शनासह अर्ज करा",
    how3_desc: "लाभ मिळवण्यासाठी चरण-दर-चरण मदत मिळवा",
  },
};